include ../../make/mods.mk

$(info LIBTARP_UTILS_OBJS is $(LIBTARP_UTILS_OBJS))

$(LIBTARP_UTILS.SO): $()
	$(CC) $(CFLAGS) $(CPPFLAGS) -shared $(LIBTARP_UTILS_OBJS) -o $(STAGING_DIR)/usr/lib/$(LIBTARP_UTILS_SO)


